language: ruby
rvm:
  - 2.4.1
# safelist
install: gem install jekyll
script: bash ./deploy.sh
sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build
